export const BasicBlocks = [
  { id: 'text', label: 'Paragraph', html: '<p data-customizable data-custom-key="text-block" style="padding:16px 40px;font-size:1rem;line-height:1.75;color:#374151">Your paragraph text goes here. Click to edit this content directly in the canvas.</p>' },
  { id: 'heading', label: 'Heading', html: '<h2 data-customizable data-custom-key="heading" style="padding:16px 40px;font-size:2rem;font-weight:bold;color:#111827">Your Section Heading</h2>' },
  { id: 'button', label: 'Button', html: '<div style="padding:16px 40px"><a href="#" data-customizable data-custom-key="button" style="display:inline-block;padding:12px 28px;background:#6366f1;color:#fff;border-radius:12px;font-weight:bold;text-decoration:none;font-size:0.9rem">Click Me</a></div>' },
  { id: 'image', label: 'Image', html: '<div data-customizable data-custom-key="image-block" style="padding:16px 40px"><img src="https://placehold.co/1200x500/6366f1/ffffff?text=Your+Image" alt="Image" style="width:100%;height:auto;border-radius:12px;display:block" /></div>' },
  { id: 'columns2', label: '2 Columns', html: '<div data-customizable data-custom-key="cols2" style="display:grid;grid-template-columns:1fr 1fr;gap:24px;padding:40px"><div data-customizable data-custom-key="col2-left" style="padding:24px;background:#f3f4f6;border-radius:12px"><h3 style="margin:0 0 8px">Column 1</h3><p style="margin:0;color:#6b7280">Your content here</p></div><div data-customizable data-custom-key="col2-right" style="padding:24px;background:#f3f4f6;border-radius:12px"><h3 style="margin:0 0 8px">Column 2</h3><p style="margin:0;color:#6b7280">Your content here</p></div></div>' },
  { id: 'columns3', label: '3 Columns', html: '<div data-customizable data-custom-key="cols3" style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:20px;padding:40px"><div data-customizable data-custom-key="col3-a" style="padding:20px;background:#f3f4f6;border-radius:12px">Col 1</div><div data-customizable data-custom-key="col3-b" style="padding:20px;background:#f3f4f6;border-radius:12px">Col 2</div><div data-customizable data-custom-key="col3-c" style="padding:20px;background:#f3f4f6;border-radius:12px">Col 3</div></div>' },
  { id: 'contact', label: 'Contact Form', html: '<section data-customizable data-custom-key="contact" style="padding:60px 40px;background:#f9fafb"><h2 style="text-align:center;margin:0 0 32px;font-size:1.75rem;font-weight:bold">Contact Us</h2><form style="max-width:480px;margin:0 auto;display:flex;flex-direction:column;gap:16px"><input placeholder="Your Name" style="padding:12px 16px;border:1px solid #e5e7eb;border-radius:8px;font-size:1rem" /><input type="email" placeholder="Email Address" style="padding:12px 16px;border:1px solid #e5e7eb;border-radius:8px;font-size:1rem" /><textarea rows="4" placeholder="Your message…" style="padding:12px 16px;border:1px solid #e5e7eb;border-radius:8px;font-size:1rem;resize:vertical"></textarea><button style="padding:14px;background:#6366f1;color:#fff;border:none;border-radius:8px;font-weight:bold;cursor:pointer">Send Message</button></form></section>' },
  { id: 'video', label: 'Video Embed', html: '<div data-customizable data-custom-key="video" style="padding:40px;background:#111"><div style="position:relative;padding-bottom:56.25%;height:0;border-radius:12px;overflow:hidden"><iframe src="https://www.youtube.com/embed/dQw4w9WgXcQ" style="position:absolute;top:0;left:0;width:100%;height:100%;border:0" allowfullscreen></iframe></div></div>' },
  { id: 'divider', label: 'Divider', html: '<div style="padding:0 40px"><hr data-customizable data-custom-key="divider" style="border:none;border-top:1px solid #e5e7eb;margin:16px 0" /></div>' },
]
